name: Jekyll site CI

on:
  push:
    branches: [ "master" ] # Or your default branch
  pull_request:
    branches: [ "master" ] # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Specify your Ruby version if needed, else defaults to a common one
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master' # Only deploy from main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # If you're using a custom domain, add it here
          # cname: your.custom.domain.com 